{
 "title": "Books API",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "route",
    "label": "API route",
    "query": {
     "query": "label_values(books_api_request_duration_milliseconds_count{app=\"Books.api\"},http_route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\r\nhistogram_quantile(0.5, sum by(le) (rate(books_api_request_duration_milliseconds_bucket[$__rate_interval])))\r\n  and on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"}))\r\n) or on() (\r\n  histogram_quantile(0.5, sum by(le) (rate(books_api_request_duration_milliseconds_bucket{http_route=\"${route}\"}[$__rate_interval])))\r\n  unless on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"}))\r\n)\r\n",
     "legendFormat": "p50"
    },
    {
     "expr": "(\r\n  histogram_quantile(0.75, sum by(le) (rate(books_api_request_duration_milliseconds_bucket[$__rate_interval])))\r\n  and on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"}))\r\n) or on() (\r\n  histogram_quantile(0.75, sum by(le) (rate(books_api_request_duration_milliseconds_bucket{http_route=\"${route}\"}[$__rate_interval])))\r\n  unless on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"}))\r\n)\r\n",
     "legendFormat": "p75"
    },
    {
     "expr": "(\r\n  histogram_quantile(0.90, sum by(le) (rate(books_api_request_duration_milliseconds_bucket[$__rate_interval])))\r\n  and on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"}))\r\n) or on() (\r\n  histogram_quantile(0.90, sum by(le) (rate(books_api_request_duration_milliseconds_bucket{http_route=\"${route}\"}[$__rate_interval])))\r\n  unless on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"}))\r\n)\r\n",
     "legendFormat": "p90"
    },
    {
     "expr": "(\r\n  histogram_quantile(0.95, sum by(le) (rate(books_api_request_duration_milliseconds_bucket[$__rate_interval])))\r\n  and on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"}))\r\n) or on() (\r\n  histogram_quantile(0.95, sum by(le) (rate(books_api_request_duration_milliseconds_bucket{http_route=\"${route}\"}[$__rate_interval])))\r\n  unless on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"}))\r\n)\r\n",
     "legendFormat": "p95"
    },
    {
     "expr": "(\r\n  histogram_quantile(0.98, sum by(le) (rate(books_api_request_duration_milliseconds_bucket[$__rate_interval])))\r\n  and on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"}))\r\n) or on() (\r\n  histogram_quantile(0.98, sum by(le) (rate(books_api_request_duration_milliseconds_bucket{http_route=\"${route}\"}[$__rate_interval])))\r\n  unless on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"}))\r\n)\r\n",
     "legendFormat": "p98"
    },
    {
     "expr": "(\r\n  histogram_quantile(0.99, sum by(le) (rate(books_api_request_duration_milliseconds_bucket[$__rate_interval])))\r\n  and on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"}))\r\n) or on() (\r\n  histogram_quantile(0.99, sum by(le) (rate(books_api_request_duration_milliseconds_bucket{http_route=\"${route}\"}[$__rate_interval])))\r\n  unless on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"}))\r\n)\r\n",
     "legendFormat": "p99"
    },
    {
     "expr": "(\r\n  histogram_quantile(0.999, sum by(le) (rate(books_api_request_duration_milliseconds_bucket[$__rate_interval])))\r\n  and on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"}))\r\n) or on() (\r\n  histogram_quantile(0.999, sum by(le) (rate(books_api_request_duration_milliseconds_bucket{http_route=\"${route}\"}[$__rate_interval])))\r\n  unless on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"}))\r\n)\r\n",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Request Rate (Requests/Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(\r\n  sum by(http_route) (rate(books_api_request_duration_milliseconds_count[1m]))\r\n  and on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"}))\r\n) or on() (\r\n  sum by(http_route) (rate(books_api_request_duration_milliseconds_count{http_route=\"${route}\"}[1m]))\r\n  unless on()\r\n  (absent(_{_=\"All\"}) and absent(_{_=\"$route\"})) or on() vector(0)\r\n)",
     "legendFormat": "{{http_request_operation}}"
    }
   ]
  },
  {
   "title": "Cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "books_api_cache_hit_total/books_api_cache_counter_total*100\r\n",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(books_api_request_duration_milliseconds_count{http_route=\"${route}\", http_response_status_code!~\"2..\"}[$__rate_interval]) or vector(0)) / sum(rate(books_api_request_duration_milliseconds_count{http_route=\"${route}\"}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(books_api_request_duration_milliseconds_count{http_route=\"${route}\", http_response_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(books_api_request_duration_milliseconds_count{http_route=\"${route}\"}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(books_api_request_duration_milliseconds_count{http_route=\"${route}\", http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(books_api_request_duration_milliseconds_count{http_route=\"${route}\"}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "5XX"
    }
   ]
  }
 ]
}