apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: apps
type: Opaque
stringData:
  JWT_SECRET_KEY: "+/V>a?RRyYz%&T0U&j%(0C$Cl^*0!Z3SWE3yxmJ>6LT"
  ConnectionStrings__db_cred: "User Id=root;Password=root;"
  MYSQL_ROOT_PASSWORD: "root"

