apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    processors:
      filter:
        metrics:
          exclude:
            match_type: expr
            expressions:
              - attributes["url.path"] == "/metrics"
              - attributes["http_request_operation"] == '"GET:/metrics"'

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        metric_expiration: 5m
      otlp:
        endpoint: jaegertracing:4317
        tls:
          insecure: true

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [filter]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          exporters: [otlp]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:0.77.0
          args:
            - --config=/etc/otel-collector-config.yaml
          ports:
            - containerPort: 4317
            - containerPort: 8888
            - containerPort: 8889
            - containerPort: 13133
          readinessProbe:
            tcpSocket:
              port: 4317
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 4317
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
      volumes:
        - name: otel-config
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observability
spec:
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: metrics-internal
      port: 8888
      targetPort: 8888
    - name: metrics-exporter
      port: 8889
      targetPort: 8889
    - name: health
      port: 13133
      targetPort: 13133
  type: ClusterIP


