<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>BooksAPI.IntegrationTests</AssemblyName>
		<RootNamespace>BooksAPI.IntegrationTests</RootNamespace>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>

		<CollectCoverage>true</CollectCoverage>
		<CoverletOutputFormat>lcov</CoverletOutputFormat>
		<CoverletOutput>./lcov.info</CoverletOutput>

		<UserSecretsId>07676ae7-1d9e-4fc6-ac56-f17f7e9c5ec3</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4"/>
		<PackageReference Include="coverlet.msbuild" Version="6.0.4">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.20" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0"/>
		<PackageReference Include="xunit.core" Version="2.5.3"/>
		<PackageReference Include="xunit.assert.source" Version="2.5.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.5.3"/>
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit"/>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\WebAPI\WebAPI.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="..\..\.dockerignore">
	    <Link>.dockerignore</Link>
	  </Content>
	  <Content Include="..\..\Common\JwtHelperService\Config\JwtConfig.json">
	    <Link>Config\JwtConfig.json</Link>
	  </Content>
	</ItemGroup>

</Project>
